#Dockerfile

FROM ubuntu

MAINTAINER raviteja

RUN apt-get update \
    && apt-get install -y openjdk-8-jdk

ADD https://get.jenkins.io/war-stable/2.249.2/jenkins.war

EXPOSE 8080

ENTRYPOINT ["java","-jar","jenkins.war"]






docker-compose.yml
---
version: '3'
services:
 jenkins1:
  build:
    context: /root/label/       #path of dockerfile
    dockerfile: Docker-jenkins-ubuntu  # dockerfile saved as Docker-jenkins-ubuntu in the above folder
  image: jenkins-ubuntu  # it gives custom name as we desired to the images created from above steps
    volumes:
    - root_db_data:/var/jenkins_home     #mounting existing volume i.e., root_db_data
  ports:
    - "8080:8080"
volumes:
 root_db_data:     
  external: True    #external mount volume verification i.e., root_db_data is present
...