version: '3.8'   #secrets option won't work in version 3
services:
  postgresDB:
    image: postgres
#this is using file base secrets making method meanns we create a file which has our username and password in different file "go to last secrets where we mentioned text files"
    secrets:
      -  db-username        #inside container where secrets get stored
      -  db-password        #inside container where our secret get stored 
    environment:
      POSTGRES_USER_FILE: /run/secrets/db-username  #path inside container
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password

  centOS:
    image: centos
    deploy:
      mode: replicated
      replicas: 1
    entrypoint: /bin/sh
    stdin_open: True
    tty: True
#creating secrets by CLI method ---> (echo "secret-string" | docker secret create my-secrets -) ---this we need to apply before executing the YAML file
    secrets:
      -  source: my-secrets

secrets:
  db-username:
    file: ./postgres_user.txt       #this file need to be present on the path with name postgre_user.txt
  db-password:  
    file: ./postgres_password.txt   #this file need to be present on the path with name postgres_password.txt
  my-secrets:
    external: True                  #using existing secret file
