version: '3'
services:
  postgresDB:
    image: postgres

    secrets:
      -  db-username
      -  db-password
    environment:
      POSTGRES_USER_FILE: /run/secrets/db-username
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
    
secrets:
  db-username:
    file: ./postgres_user.txt
  db-password:
    file: ./postgres_passwd.txt
